services:
  - type: web
    name: eduadmin-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn appfinal:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY  
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: sqlite:///educational_dashboard.db